# proto-file: intrinsic/world/public/proto/object_world_updates.proto
# proto-message: intrinsic_proto.world.ObjectWorldUpdates

updates: {
  update_transform {
    node_a {
      by_name {
        object {
          object_name: "enclosure"
        }
      }
    }
    node_b {
      by_name {
        object {
          object_name: "ur_module"
        }
      }
    }
    node_to_update: {
      by_name {
        object {
          object_name: "ur_module"
        }
      }
    }
    a_t_b {
      position {
        x: 0.32
        y: 0.685
        z: 0.658
      }
      orientation {
        x: 0
        y: 0
        z: 0
        w: 1
      }
    }
  }
}