# proto-file: intrinsic/world/public/proto/object_world_updates.proto
# proto-message: intrinsic_proto.world.ObjectWorldUpdates

updates {
  create_frame {
    new_frame_name: "grasp"
    parent_t_new_frame {
      position {
        x: 0.15
        y: 0.25
        z: 0.71
      }
      orientation {
        x: 1.0
      }
    }
    parent_object_with_filter {
      reference {
        by_name {
          object_name: "root"
        }
      }
    }
  }
}
updates {
  create_frame {
    new_frame_name: "pre_grasp"
    parent_t_new_frame {
      position {
        x: 0.15
        y: 0.25
        z: 0.73
      }
      orientation {
        x: 1.0
      }
    }
    parent_object_with_filter {
      reference {
        by_name {
          object_name: "root"
        }
      }
    }
  }
}
updates {
  create_frame {
    new_frame_name: "pre_place_vise"
    parent_t_new_frame {
      position {
        x: 0.47
        y: 0.37
        z: 0.78
      }
      orientation {
        x: 0.7071
        y: 0.7071
      }
    }
    parent_object_with_filter {
      reference {
        by_name {
          object_name: "root"
        }
      }
    }
  }
}
updates {
  create_frame {
    new_frame_name: "place_vise"
    parent_t_new_frame {
      position {
        x: 0.47
        y: 0.37
        z: 0.7
      }
      orientation {
        x: 0.7071
        y: 0.7071
      }
    }
    parent_object_with_filter {
      reference {
        by_name {
          object_name: "root"
        }
      }
    }
  }
}
updates {
  create_frame {
    new_frame_name: "machine_approach"
    parent_t_new_frame {
      position {
        x: 0.35
        y: 0.4
        z: 0.8
      }
      orientation {
        x: 0.7071
        y: 0.7071
      }
    }
    parent_object_with_filter {
      reference {
        by_name {
          object_name: "root"
        }
      }
    }
  }
}
updates {
  create_frame {
    new_frame_name: "view"
    parent_t_new_frame {
      position {
        x: 0.3433
        y: 0.3786
        z: 0.88
      }
      orientation {
        x: -0.2667
        y: -0.9585
        z: 0.1
        w: 0.0092
      }
    }
    parent_object_with_filter {
      reference {
        by_name {
          object_name: "root"
        }
      }
    }
  }
}
updates {
  update_transform {
    node_a {
      by_name {
        object {
          object_name: "root"
        }
      }
    }
    node_b {
      by_name {
        object {
          object_name: "raw_stock_2x3x5"
        }
      }
    }
    node_to_update {
      by_name {
        object {
          object_name: "raw_stock_2x3x5"
        }
      }
    }
    a_t_b {
      position {
        x: 0.25
        y: 0.25
        z: 0.71
      }
      orientation {
        x: 0.6830
        y: 0.1830
        z: 0.6830
        w: -0.1830
      }
    }
  }
}
