// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This binary implements the ability to load a docker image, calculate its image manifest sha256 hash and output a digest file.
package main

import (
	"flag"
	"io/ioutil"
	"os"

	"intrinsic/production/intrinsic"

	log "github.com/golang/glog"
	"github.com/google/go-containerregistry/pkg/v1/tarball"
)

var (
	flagDst        = flag.String("dst", "", "The destination location of the digest file to write to.")
	flagImgTarball = flag.String("tarball", "", "Path to the image tarball as generated by docker save. Required if --config was not specified.")
)

func main() {
	intrinsic.Init()

	if *flagDst == "" || *flagImgTarball == "" {
		log.Fatalf("usage: digester -dst=path/to/output.txt -tarball=path/to.tar")
	}
	imageRef, err := tarball.ImageFromPath(*flagImgTarball, nil)
	if err != nil {
		log.Fatalf("loading %s as docker image: %v", *flagImgTarball, err)
	}
	d, err := imageRef.Digest()
	if err != nil {
		log.Fatalf("getting digest for %s: %v", *flagImgTarball, err)
	}
	if err := ioutil.WriteFile(*flagDst, []byte(d.String()), os.ModePerm); err != nil {
		log.Fatalf("Error outputting digest file to %s: %v", *flagDst, err)
	}
}
