// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.data_store.internal;

option go_package = "intrinsic/kubernetes/data_store/bolt_adapter/bolt_record_go_proto";

// Message that describes at-rest serialization in BoltDB.
message BoltRecord {
  string revision = 1;

  // Allow different serialization strategies.
  oneof data {
    // Database entry serialized as Protobuf wire format.
    bytes data_as_proto_wire = 3;
  }

  reserved 2;
}
