// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package generatedpodsuffix contains a helper function for removing an
// autogenerated suffix from a pod name.
package generatedpodsuffix

import (
	"regexp"
)

// I saw some pods with a {9}-{5}, and some with a {10}-{5} suffix in the wild.
// So let's be more lenient with the lengths here.
var reWithoutAutogeneratedSuffix = regexp.MustCompile(`^([a-z0-9-.]+)-[a-z0-9]{8,12}-[a-z0-9]{4,6}$`)

// Trim the autogenerated suffix from a pod name, e.g.
// "robot1-sim-647ffb8f67-kwwtm" -> "robot1-sim".
func Trim(s string) string {
	return reWithoutAutogeneratedSuffix.ReplaceAllString(s, "$1")
}
