apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: artifacts-containerd
spec:
  lookupPolicy:
    local: false
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: artifacts-containerd
spec:
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: docker.io/library/alpine:3.22
  output:
    to:
      kind: ImageStreamTag
      name: artifacts-containerd:pilot
  triggers: []
