# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-store
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: data-store
    spec:
      automountServiceAccountToken: false
      containers:
        - name: hot-shared-state
          image: {{ .Values.registry }}{{ .Values.images.hot_shared_state }}
          args:
            - /intrinsic/storage/hot_shared_state/hot_shared_state_main
            - --port_hss=9777
            - --port_intrinsic_db=9757  # DO NOT EXPOSE to the outside world!
            - --cloud_intrinsic_db_address={{ .Values.domain }}:443
            - --polymorphic_data_frontend_address=localhost:9747  # Change if the PDF is moved to a different pod.
            - --cluster_name={{ .Values.robot.name }}
            - --opencensus_metrics_port=9101
            - --opencensus_tracing={{ .Values.opencensus_tracing }}
            - --trace_probability=0.01
            - --bolt_path=/mnt/intrinsic-db/intrinsic.db
            {{ if .Values.feature_options.disable_cluster_doc_backup }}
            - --disable_cluster_doc_backup=true
            {{ end }}
            {{ if eq .Values.feature_options.base_config "DEV" }}
            - --v=2
            {{ end }}
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: intrinsic-db-dir
              mountPath: /mnt/intrinsic-db
        - name: onprem-cas
          image: {{ .Values.registry }}{{ .Values.images.local_cas }}
          args:
            - /intrinsic/storage/onprem_cas/cmd/localcas
            - --port=9747
            - --objects_dir=/mnt/onpremcas/storage
            - --partial_dir=/mnt/onpremcas/partial
            {{ if eq .Values.feature_options.base_config "DEV" }}
            - --v=2
            {{ end }}
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: onprem-cas
              mountPath: /mnt/onpremcas
      volumes:
        - name: intrinsic-db-dir
          hostPath:
            path: /var/apps/intrinsic-db
            type: DirectoryOrCreate
        - name: onprem-cas
          persistentVolumeClaim:
            claimName: onprem-cas
---
apiVersion: v1
kind: Service
metadata:
  name: hot-shared-state
  labels:
    app: data-store
spec:
  type: ClusterIP
  ports:
    - port: 9777
      name: grpc-hot-shared-state
  selector:
    app: data-store
---
apiVersion: v1
kind: Service
metadata:
  name: content-addressable-storage
  labels:
    app: data-store
spec:
  type: ClusterIP
  ports:
    - port: 9747
      name: grpc-content-addressable-storage
  selector:
    app: data-store
---
apiVersion: v1
kind: Service
metadata:
  name: onprem-cas
  labels:
    app: data-store
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 9747
      name: grpc-onprem-cas
  selector:
    app: data-store
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onprem-cas
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: content-addressable-storage
spec:
  hosts:
    - "*"
  gateways:
    - app-ingress/gateway
  http:
    - match:
        - uri:
            prefix: /intrinsic_proto.content_addressable_storage.v1.ContentAddressableStorageService/
      route:
        - destination:
            host: content-addressable-storage
            port:
              number: 9747
