# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: skill-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skill-registry
  template:
    metadata:
      labels:
        app: skill-registry
        platform.intrinsic.ai/skill-registry: "true"
    spec:
      serviceAccount: skill-registry
      serviceAccountName: skill-registry
      containers:
        - name: skill-registry
          image: {{ .Values.registry }}{{ .Values.images.skill_registry }}
          args:
            - /intrinsic/skills/tools/skillregistryservice_main
            - --logtostderr
            - --runtime_db_service_address=runtime-db.app-intrinsic-base.svc.cluster.local:8080
            - --port=8080
            - --opencensus_metrics_port=9101
            - --opencensus_tracing={{ .Values.opencensus_tracing }}
            {{ if eq .Values.project "intrinsic-integration-tests" }}
            - --trace_probability=0.001  # See the reasoning in b/321192011
            {{ else }}
            - --trace_probability=1.0
            {{ end }}
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
---
apiVersion: v1
kind: Service
metadata:
  name: skill-registry
  labels:
    app: skill-registry
spec:
  clusterIP: None
  ports:
    - port: 8080
      name: grpc-skill-registry
  selector:
    app: skill-registry
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: skill-registry-metrics
  labels:
    app: skill-registry-metrics
spec:
  clusterIP: None
  ports:
    - port: 9101
      name: http-metrics
  selector:
    app: skill-registry
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: skill-registry-metrics
  labels:
    prometheus: kube-prometheus
spec:
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 10s
      metricRelabelings:   # This solves high cardinality labeling issue in prometheus tsdb, reach out to intrinsic-data-infra before removing
        - action: labeldrop
          regex: pod
  selector:
    matchLabels:
      app: skill-registry-metrics
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: skill-registry
spec:
  hosts:
    - "*"
  gateways:
    - app-ingress/gateway
  http:
    - match:
        - uri:
            prefix: /intrinsic_proto.skills.SkillRegistryInternal/
        - uri:
            prefix: /intrinsic_proto.skills.SkillRegistry/
        - uri:
            prefix: /intrinsic_proto.skills.BehaviorTreeRegistryInternal/
        - uri:
            prefix: /intrinsic_proto.skills.BehaviorTreeRegistry/
      route:
        - destination:
            host: skill-registry
            port:
              number: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skill-registry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skill-registry
rules:
  # skillcomposer: read info from `skill-registry-config` configmaps
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: skill-registry
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: skill-registry
subjects:
  - kind: ServiceAccount
    name: skill-registry
    namespace: {{ .Release.Namespace }}
