# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Executive Helm templates

package(default_visibility = [
    "//visibility:public",
])

filegroup(
    name = "code-execution-template",
    srcs = ["code-execution.yaml"],
    visibility = ["//intrinsic_runtime/kubernetes/intrinsic_base:__pkg__"],
)

filegroup(
    name = "executive-template",
    srcs = ["executive.yaml"],
    visibility = ["//intrinsic_runtime/kubernetes/intrinsic_base:__pkg__"],
)
