# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This package contains a data store service implementation which is only a shim forwarding all
# requests to Firestore.

load("//bazel:go_macros.bzl", "go_library")

go_library(
    name = "firestoreshimtypes",
    srcs = ["firestore_shim_types.go"],
    importpath = "intrinsic/kubernetes/data_store/firestore_shim/firestoreshimtypes",
    visibility = ["//intrinsic/kubernetes/data_store:__subpackages__"],
    deps = [
        "//intrinsic/kubernetes/data_store:revision",
        "//intrinsic/kubernetes/data_store/proto:filter_spec_go_proto",
        "@com_google_cloud_go_firestore//:firestore",
        "@org_golang_google_protobuf//proto",
    ],
)
