// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package clusterservice contains an
// implementation of the data store service for Cluster protos.
package clusterservice

import (
	"context"
	"fmt"
	"path"

	"intrinsic/config/collections"
	"intrinsic/config/convertrunnables"
	"intrinsic/kubernetes/data_store/revision"

	log "github.com/golang/glog"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	pb "intrinsic/config/proto/cluster_go_proto"
	commonpb "intrinsic/config/proto/common_go_proto"
	svcpb "intrinsic/kubernetes/data_store/proto/cluster_service_go_proto"

	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// extractIdentifiersFromProto extracts the identifier tuple from a given proto.
// If an identifier is missing in the proto, set its value to an empty string.
// The pointer to the proto is guaranteed to be non-nil.
func extractIdentifiersFromProto(p *pb.Cluster) *identifiers {
	return &identifiers{name: p.GetMetadata().GetName()}
}

// writeIdentifiersToProto writes the identifier tuple to a proto. Create empty
// nested submessages if required (e.g. if an identifier is a field of a
// submessage). The pointer to the proto is guaranteed to be non-nil. The
// identifiers struct is guaranteed to be valid.
func writeIdentifiersToProto(ids *identifiers, p *pb.Cluster) {
	if p.GetMetadata() == nil {
		p.Metadata = &commonpb.Metadata{}
	}
	p.GetMetadata().Name = ids.name
}

// extractIdentifiersFromDocumentID extracts the identifier tuple from the
// document ID. If this is not possible, return an empty struct.
func extractIdentifiersFromDocumentID(documentID string) *identifiers {
	return &identifiers{name: documentID}
}

// convertIdentifiersToDocumentID creates a document ID from the identifiers
// struct. This conversion must be collision-free (i.e., two different
// identifier structs must have different document IDs) in practice (i.e.
// via hashing). However, it must not necessarily be reversible (e.g. because
// of hashing).
func convertIdentifiersToDocumentID(ids *identifiers) string {
	return ids.name
}

// onIngress is called on ingress into IntrinsicDB, e.g. during a "Set"
// operation. It is called  BEFORE the identifiers are autogenerated
// (if enabled).
func onIngress(p *pb.Cluster) error {
	if p.GetApplication().GetProcess() == nil {
		return nil
	}
	if err := convertrunnables.MoveRunnablesToBytes(p.GetApplication().GetProcess()); err != nil {
		return status.Errorf(codes.Internal, "on ingress: could not convert runnables to bytes: %v", err)
	}
	return nil
}

// onEgress is called on egress from IntrinsicDB, e.g. during a "Get", "List",
// but also "Set" operation (on retrieval of the proto after it has been set).
// It is called BEFORE the identifiers are recovered from the document ID
// (if enabled).
func onEgress(p *pb.Cluster) error {
	if p.GetApplication().GetProcess() == nil {
		return nil
	}
	if err := convertrunnables.MoveBytesToRunnables(p.GetApplication().GetProcess()); err != nil {
		return status.Errorf(codes.Internal, "on egress: could not convert bytes to runnables: %v", err)
	}
	return nil
}

func (s *ClusterService) GetClusterOnprem(ctx context.Context, req *svcpb.GetClusterRequest) (*svcpb.GetClusterResponse, error) {
	if s.ba == nil {
		return nil, errBoltAdapterIsNil
	}
	ids, err := extractIdentifiersFromRequest(req)
	if err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid request: %v", err)
	}
	docID := convertIdentifiersToDocumentID(ids)

	uri := path.Join(clustersCollection, docID)

	p := &pb.Cluster{}
	token, err := s.ba.GetDocumentAsType(ctx, uri, p)
	if err != nil {
		return nil, status.Errorf(codes.Unknown, "could not retrieve Cluster from a BoltDB document at %q: %v", uri, err)
	}
	if token.IsEmpty() {
		return nil, status.Errorf(codes.NotFound, "no document %s", uri)
	}
	if err := onEgress(p); err != nil {
		return nil, err
	}
	// We've already checked the validity of identifiers.
	writeIdentifiersToProto(ids, p)

	res := &svcpb.GetClusterResponse{}
	res.Cluster = p
	res.RevisionToken = token.String()
	return res, nil
}

func (s *ClusterService) SetClusterOnprem(ctx context.Context, req *svcpb.SetClusterRequest) (*svcpb.SetClusterResponse, error) {
	if req.Cluster == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid request: %v", errNoClusterGiven)
	}
	if s.ba == nil {
		return nil, errBoltAdapterIsNil
	}

	p := req.GetCluster()

	if p.GetMetadata().GetIsIncomplete() {
		return nil, status.Error(codes.InvalidArgument, "invalid request: cannot save an incomplete document")
	}

	if err := onIngress(p); err != nil {
		return nil, err
	}

	if p.GetMetadata() == nil {
		p.Metadata = &commonpb.Metadata{}
	}
	// Add this info only if the field was not provided by the client.
	if p.GetMetadata().GetLastUpdatedBy() == "" {
		if u, err := userCurrent(); err == nil {
			p.GetMetadata().LastUpdatedBy = u.Username
		} else {
			log.WarningContextf(ctx, "Failed to get user information: %v", err)
			p.GetMetadata().LastUpdatedBy = "IntrinsicDB"
		}
	}
	p.GetMetadata().UpdateTime = timestamppb.New(timeNow().UTC())
	n := p.GetMetadata().GetName()
	if n == "" {
		return nil, status.Error(codes.InvalidArgument, "invalid request: cluster name is empty")
	}
	uri := fmt.Sprintf("%s/%s", collections.Clusters, n)

	token := revision.FromString(req.GetRevisionToken())
	pOut := &pb.Cluster{}

	if err := s.ba.SetDocumentAsType(ctx, uri, token, req.GetOverwrite(), p); err != nil {
		return nil, status.Errorf(revision.ToCanonicalCode(err), "cannot set cluster document in BoltDB: %v", err)
	}
	token, err := s.ba.GetDocumentAsType(ctx, uri, pOut)
	if err != nil {
		return nil, status.Errorf(codes.Unknown, "could not retrieve the updated Firestore document: %v", err)
	}
	if err := onEgress(pOut); err != nil {
		return nil, err
	}
	res := &svcpb.SetClusterResponse{
		Cluster:       pOut,
		RevisionToken: token.String(),
	}
	return res, nil
}
